# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Harivony\Desktop\CakeFLow_Project\Cakeflow\app\ui\Dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DashboardWindow(object):
    def setupUi(self, DashboardWindow):
        DashboardWindow.setObjectName("DashboardWindow")
        DashboardWindow.resize(1200, 800)
        DashboardWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #faf5f7;\n"
"}")
        self.centralWidget = QtWidgets.QWidget(DashboardWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.mainLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.sidebarContainer = QtWidgets.QFrame(self.centralWidget)
        self.sidebarContainer.setMinimumSize(QtCore.QSize(240, 0))
        self.sidebarContainer.setMaximumSize(QtCore.QSize(240, 16777215))
        self.sidebarContainer.setStyleSheet("QFrame#sidebarContainer {\n"
"    background-color: #ffffff;\n"
"    border-right: 1px solid #f0e0e8;\n"
"}")
        self.sidebarContainer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sidebarContainer.setObjectName("sidebarContainer")
        self.mainLayout.addWidget(self.sidebarContainer)
        self.contentArea = QtWidgets.QFrame(self.centralWidget)
        self.contentArea.setStyleSheet("QFrame#contentArea {\n"
"    background-color: #faf5f7;\n"
"}")
        self.contentArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentArea.setObjectName("contentArea")
        self.contentLayout = QtWidgets.QVBoxLayout(self.contentArea)
        self.contentLayout.setContentsMargins(0, 0, 0, 0)
        self.contentLayout.setSpacing(0)
        self.contentLayout.setObjectName("contentLayout")
        self.headerContainer = QtWidgets.QFrame(self.contentArea)
        self.headerContainer.setMinimumSize(QtCore.QSize(0, 70))
        self.headerContainer.setMaximumSize(QtCore.QSize(16777215, 70))
        self.headerContainer.setStyleSheet("QFrame#headerContainer {\n"
"    background-color: #ffffff;\n"
"    border-bottom: 1px solid #f0e0e8;\n"
"}")
        self.headerContainer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.headerContainer.setObjectName("headerContainer")
        self.contentLayout.addWidget(self.headerContainer)
        self.pagesStack = QtWidgets.QStackedWidget(self.contentArea)
        self.pagesStack.setStyleSheet("QStackedWidget {\n"
"    background-color: #faf5f7;\n"
"}")
        self.pagesStack.setObjectName("pagesStack")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.homeLayout = QtWidgets.QVBoxLayout(self.homePage)
        self.homeLayout.setContentsMargins(25, 25, 25, 25)
        self.homeLayout.setObjectName("homeLayout")
        self.welcomeLabel = QtWidgets.QLabel(self.homePage)
        self.welcomeLabel.setStyleSheet("QLabel {\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    color: #c2185b;\n"
"}")
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.homeLayout.addWidget(self.welcomeLabel)
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.homeLayout.addItem(spacerItem)
        self.pagesStack.addWidget(self.homePage)
        self.contentLayout.addWidget(self.pagesStack)
        self.mainLayout.addWidget(self.contentArea)
        DashboardWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(DashboardWindow)
        QtCore.QMetaObject.connectSlotsByName(DashboardWindow)

    def retranslateUi(self, DashboardWindow):
        _translate = QtCore.QCoreApplication.translate
        DashboardWindow.setWindowTitle(_translate("DashboardWindow", "Délice et Douceur chez A - Dashboard"))
        self.welcomeLabel.setText(_translate("DashboardWindow", "Bienvenue sur CakeFlow"))
import resources_rc
