# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Harivony\Desktop\CakeFLow_Project\Cakeflow\app\ui\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(1000, 650)
        LoginWindow.setMinimumSize(QtCore.QSize(900, 600))
        LoginWindow.setStyleSheet("QWidget#LoginWindow {\n"
"    background-color: #fff5f7;\n"
"}")
        self.mainLayout = QtWidgets.QHBoxLayout(LoginWindow)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.leftPanel = QtWidgets.QFrame(LoginWindow)
        self.leftPanel.setMinimumSize(QtCore.QSize(420, 0))
        self.leftPanel.setMaximumSize(QtCore.QSize(420, 16777215))
        self.leftPanel.setStyleSheet("QFrame#leftPanel {\n"
"    background-color: #fce4ec;\n"
"    border: none;\n"
"    border-right: 3px solid #e91e90;\n"
"    border-top-right-radius: 40px;\n"
"    border-bottom-right-radius: 40px;\n"
"}")
        self.leftPanel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftPanel.setObjectName("leftPanel")
        self.leftLayout = QtWidgets.QVBoxLayout(self.leftPanel)
        self.leftLayout.setContentsMargins(0, 0, 0, 0)
        self.leftLayout.setSpacing(0)
        self.leftLayout.setObjectName("leftLayout")
        self.imageLabel = QtWidgets.QLabel(self.leftPanel)
        self.imageLabel.setText("")
        self.imageLabel.setPixmap(QtGui.QPixmap(":/images/login_cake_long.jpg"))
        self.imageLabel.setScaledContents(True)
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setStyleSheet("QLabel#imageLabel {\n"
"    border-top-right-radius: 40px;\n"
"    border-bottom-right-radius: 40px;\n"
"}")
        self.imageLabel.setObjectName("imageLabel")
        self.leftLayout.addWidget(self.imageLabel)
        self.mainLayout.addWidget(self.leftPanel)
        self.rightPanel = QtWidgets.QFrame(LoginWindow)
        self.rightPanel.setStyleSheet("QFrame#rightPanel {\n"
"    background-color: #fff5f7;\n"
"    border: none;\n"
"}")
        self.rightPanel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rightPanel.setObjectName("rightPanel")
        self.rightLayout = QtWidgets.QVBoxLayout(self.rightPanel)
        self.rightLayout.setContentsMargins(50, 20, 50, 20)
        self.rightLayout.setSpacing(8)
        self.rightLayout.setObjectName("rightLayout")
        self.topBar = QtWidgets.QFrame(self.rightPanel)
        self.topBar.setMinimumSize(QtCore.QSize(0, 6))
        self.topBar.setMaximumSize(QtCore.QSize(16777215, 6))
        self.topBar.setStyleSheet("QFrame#topBar {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #ffb6c1, stop:1 #e91e90);\n"
"    border-radius: 3px;\n"
"}")
        self.topBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topBar.setObjectName("topBar")
        self.rightLayout.addWidget(self.topBar)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.rightLayout.addItem(spacerItem)
        self.logoIcon = QtWidgets.QLabel(self.rightPanel)
        self.logoIcon.setMinimumSize(QtCore.QSize(90, 90))
        self.logoIcon.setMaximumSize(QtCore.QSize(90, 90))
        self.logoIcon.setPixmap(QtGui.QPixmap(":/images/logo-sans-fond.png"))
        self.logoIcon.setScaledContents(True)
        self.logoIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.logoIcon.setStyleSheet("QLabel#logoIcon {\n"
"    background-color: #fce4ec;\n"
"    border: 3px solid #e91e90;\n"
"    border-radius: 45px;\n"
"    padding: 12px;\n"
"}")
        self.logoIcon.setObjectName("logoIcon")
        self.rightLayout.addWidget(self.logoIcon, 0, QtCore.Qt.AlignHCenter)
        self.titleLabel = QtWidgets.QLabel(self.rightPanel)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setStyleSheet("QLabel#titleLabel {\n"
"    font-family: \'Georgia\', \'Times New Roman\', serif;\n"
"    font-size: 28px;\n"
"    font-weight: bold;\n"
"    font-style: italic;\n"
"    color: #c2185b;\n"
"    margin-top: 5px;\n"
"    margin-bottom: 0px;\n"
"}")
        self.titleLabel.setObjectName("titleLabel")
        self.rightLayout.addWidget(self.titleLabel, 0, QtCore.Qt.AlignHCenter)
        self.subtitleLabel = QtWidgets.QLabel(self.rightPanel)
        self.subtitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitleLabel.setStyleSheet("QLabel#subtitleLabel {\n"
"    font-family: \'Georgia\', \'Times New Roman\', serif;\n"
"    font-size: 16px;\n"
"    color: #e91e90;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 5px;\n"
"}")
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.rightLayout.addWidget(self.subtitleLabel, 0, QtCore.Qt.AlignHCenter)
        self.heartSeparator = QtWidgets.QLabel(self.rightPanel)
        self.heartSeparator.setAlignment(QtCore.Qt.AlignCenter)
        self.heartSeparator.setStyleSheet("QLabel#heartSeparator {\n"
"    font-size: 14px;\n"
"    color: #e91e90;\n"
"    margin-bottom: 5px;\n"
"}")
        self.heartSeparator.setObjectName("heartSeparator")
        self.rightLayout.addWidget(self.heartSeparator, 0, QtCore.Qt.AlignHCenter)
        self.connectionLabel = QtWidgets.QLabel(self.rightPanel)
        self.connectionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.connectionLabel.setStyleSheet("QLabel#connectionLabel {\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    color: #333333;\n"
"    margin-bottom: 2px;\n"
"}")
        self.connectionLabel.setObjectName("connectionLabel")
        self.rightLayout.addWidget(self.connectionLabel, 0, QtCore.Qt.AlignHCenter)
        self.subtextLabel = QtWidgets.QLabel(self.rightPanel)
        self.subtextLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.subtextLabel.setStyleSheet("QLabel#subtextLabel {\n"
"    font-size: 12px;\n"
"    color: #888888;\n"
"    margin-bottom: 15px;\n"
"}")
        self.subtextLabel.setObjectName("subtextLabel")
        self.rightLayout.addWidget(self.subtextLabel, 0, QtCore.Qt.AlignHCenter)
        self.usernameFrame = QtWidgets.QFrame(self.rightPanel)
        self.usernameFrame.setMinimumSize(QtCore.QSize(0, 50))
        self.usernameFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.usernameFrame.setStyleSheet("QFrame#usernameFrame {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #f0c0d0;\n"
"    border-radius: 12px;\n"
"}\n"
"QFrame#usernameFrame:hover {\n"
"    border-color: #e91e90;\n"
"}")
        self.usernameFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.usernameFrame.setObjectName("usernameFrame")
        self.usernameLayout = QtWidgets.QHBoxLayout(self.usernameFrame)
        self.usernameLayout.setContentsMargins(12, -1, 12, -1)
        self.usernameLayout.setSpacing(10)
        self.usernameLayout.setObjectName("usernameLayout")
        self.userIcon = QtWidgets.QLabel(self.usernameFrame)
        self.userIcon.setMinimumSize(QtCore.QSize(24, 24))
        self.userIcon.setMaximumSize(QtCore.QSize(24, 24))
        self.userIcon.setPixmap(QtGui.QPixmap(":/icons/user.svg"))
        self.userIcon.setScaledContents(True)
        self.userIcon.setObjectName("userIcon")
        self.usernameLayout.addWidget(self.userIcon)
        self.usernameInput = QtWidgets.QLineEdit(self.usernameFrame)
        self.usernameInput.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    background: transparent;\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"    padding: 5px;\n"
"}\n"
"QLineEdit::placeholder {\n"
"    color: #bbbbbb;\n"
"}")
        self.usernameInput.setObjectName("usernameInput")
        self.usernameLayout.addWidget(self.usernameInput)
        self.rightLayout.addWidget(self.usernameFrame)
        spacerItem1 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.rightLayout.addItem(spacerItem1)
        self.passwordFrame = QtWidgets.QFrame(self.rightPanel)
        self.passwordFrame.setMinimumSize(QtCore.QSize(0, 50))
        self.passwordFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.passwordFrame.setStyleSheet("QFrame#passwordFrame {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #f0c0d0;\n"
"    border-radius: 12px;\n"
"}\n"
"QFrame#passwordFrame:hover {\n"
"    border-color: #e91e90;\n"
"}")
        self.passwordFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.passwordFrame.setObjectName("passwordFrame")
        self.passwordLayout = QtWidgets.QHBoxLayout(self.passwordFrame)
        self.passwordLayout.setContentsMargins(12, -1, 12, -1)
        self.passwordLayout.setSpacing(10)
        self.passwordLayout.setObjectName("passwordLayout")
        self.lockIcon = QtWidgets.QLabel(self.passwordFrame)
        self.lockIcon.setMinimumSize(QtCore.QSize(24, 24))
        self.lockIcon.setMaximumSize(QtCore.QSize(24, 24))
        self.lockIcon.setPixmap(QtGui.QPixmap(":/icons/lock.svg"))
        self.lockIcon.setScaledContents(True)
        self.lockIcon.setObjectName("lockIcon")
        self.passwordLayout.addWidget(self.lockIcon)
        self.passwordInput = QtWidgets.QLineEdit(self.passwordFrame)
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    background: transparent;\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"    padding: 5px;\n"
"}\n"
"QLineEdit::placeholder {\n"
"    color: #bbbbbb;\n"
"}")
        self.passwordInput.setObjectName("passwordInput")
        self.passwordLayout.addWidget(self.passwordInput)
        self.togglePasswordBtn = QtWidgets.QPushButton(self.passwordFrame)
        self.togglePasswordBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.togglePasswordBtn.setMaximumSize(QtCore.QSize(28, 28))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/eye.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.togglePasswordBtn.setIcon(icon)
        self.togglePasswordBtn.setIconSize(QtCore.QSize(20, 20))
        self.togglePasswordBtn.setFlat(True)
        self.togglePasswordBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.togglePasswordBtn.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #fce4ec;\n"
"    border-radius: 14px;\n"
"}")
        self.togglePasswordBtn.setObjectName("togglePasswordBtn")
        self.passwordLayout.addWidget(self.togglePasswordBtn)
        self.rightLayout.addWidget(self.passwordFrame)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.rightLayout.addItem(spacerItem2)
        self.loginButton = QtWidgets.QPushButton(self.rightPanel)
        self.loginButton.setMinimumSize(QtCore.QSize(0, 50))
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/login.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loginButton.setIcon(icon1)
        self.loginButton.setIconSize(QtCore.QSize(22, 22))
        self.loginButton.setStyleSheet("QPushButton#loginButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #e91e90, stop:1 #c2185b);\n"
"    color: #ffffff;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"}\n"
"QPushButton#loginButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #c2185b, stop:1 #ad1457);\n"
"}\n"
"QPushButton#loginButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #ad1457, stop:1 #880e4f);\n"
"}")
        self.loginButton.setObjectName("loginButton")
        self.rightLayout.addWidget(self.loginButton)
        self.errorLabel = QtWidgets.QLabel(self.rightPanel)
        self.errorLabel.setText("")
        self.errorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.errorLabel.setStyleSheet("QLabel#errorLabel {\n"
"    font-size: 12px;\n"
"    color: #d32f2f;\n"
"    background-color: #ffebee;\n"
"    border: 1px solid #ef9a9a;\n"
"    border-radius: 6px;\n"
"    padding: 8px 16px;\n"
"}")
        self.errorLabel.setVisible(False)
        self.errorLabel.setObjectName("errorLabel")
        self.rightLayout.addWidget(self.errorLabel, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.rightLayout.addItem(spacerItem3)
        self.footerFrame = QtWidgets.QFrame(self.rightPanel)
        self.footerFrame.setMinimumSize(QtCore.QSize(0, 60))
        self.footerFrame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.footerFrame.setStyleSheet("QFrame#footerFrame {\n"
"    background-color: #fff0f3;\n"
"    border-radius: 12px;\n"
"    border: 1px solid #fce4ec;\n"
"}")
        self.footerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footerFrame.setObjectName("footerFrame")
        self.footerLayout = QtWidgets.QHBoxLayout(self.footerFrame)
        self.footerLayout.setContentsMargins(15, -1, 15, -1)
        self.footerLayout.setObjectName("footerLayout")
        self.footerIcon = QtWidgets.QLabel(self.footerFrame)
        self.footerIcon.setMinimumSize(QtCore.QSize(36, 36))
        self.footerIcon.setMaximumSize(QtCore.QSize(36, 36))
        self.footerIcon.setPixmap(QtGui.QPixmap(":/icons/cake.svg"))
        self.footerIcon.setScaledContents(True)
        self.footerIcon.setObjectName("footerIcon")
        self.footerLayout.addWidget(self.footerIcon)
        self.footerTextLayout = QtWidgets.QVBoxLayout()
        self.footerTextLayout.setSpacing(0)
        self.footerTextLayout.setObjectName("footerTextLayout")
        self.footerTitle = QtWidgets.QLabel(self.footerFrame)
        self.footerTitle.setStyleSheet("QLabel {\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    color: #c2185b;\n"
"}")
        self.footerTitle.setObjectName("footerTitle")
        self.footerTextLayout.addWidget(self.footerTitle)
        self.footerSubtitle = QtWidgets.QLabel(self.footerFrame)
        self.footerSubtitle.setStyleSheet("QLabel {\n"
"    font-size: 11px;\n"
"    color: #999999;\n"
"}")
        self.footerSubtitle.setObjectName("footerSubtitle")
        self.footerTextLayout.addWidget(self.footerSubtitle)
        self.footerLayout.addLayout(self.footerTextLayout)
        spacerItem4 = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.footerLayout.addItem(spacerItem4)
        self.rightLayout.addWidget(self.footerFrame)
        self.mainLayout.addWidget(self.rightPanel)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Délice et Douceur chez A - Connexion"))
        self.titleLabel.setText(_translate("LoginWindow", "Délice et Douceur"))
        self.subtitleLabel.setText(_translate("LoginWindow", "——— chez A ———"))
        self.heartSeparator.setText(_translate("LoginWindow", "♥"))
        self.connectionLabel.setText(_translate("LoginWindow", "Connexion"))
        self.subtextLabel.setText(_translate("LoginWindow", "Veuillez vous connecter pour continuer"))
        self.usernameInput.setPlaceholderText(_translate("LoginWindow", "Nom d\'utilisateur"))
        self.passwordInput.setPlaceholderText(_translate("LoginWindow", "Mot de passe"))
        self.loginButton.setText(_translate("LoginWindow", "  Se connecter"))
        self.footerTitle.setText(_translate("LoginWindow", "Délice et Douceur chez A"))
        self.footerSubtitle.setText(_translate("LoginWindow", "Gestion simplifiée, saveurs maîtrisées"))
import resources_rc
