# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Harivony\Desktop\CakeFLow_Project\Cakeflow\app\ui\widgets\Card.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Card(object):
    def setupUi(self, Card):
        Card.setObjectName("Card")
        Card.resize(280, 140)
        Card.setMinimumSize(QtCore.QSize(220, 120))
        Card.setStyleSheet("QFrame#Card {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #f0e0e8;\n"
"    border-radius: 16px;\n"
"}\n"
"QFrame#Card:hover {\n"
"    border-color: #e91e90;\n"
"    background-color: #fffafc;\n"
"}")
        Card.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardLayout = QtWidgets.QVBoxLayout(Card)
        self.cardLayout.setContentsMargins(20, 18, 20, 18)
        self.cardLayout.setObjectName("cardLayout")
        self.cardHeaderLayout = QtWidgets.QHBoxLayout()
        self.cardHeaderLayout.setObjectName("cardHeaderLayout")
        self.cardTitle = QtWidgets.QLabel(Card)
        self.cardTitle.setStyleSheet("QLabel { font-size: 12px; color: #999999; }")
        self.cardTitle.setObjectName("cardTitle")
        self.cardHeaderLayout.addWidget(self.cardTitle)
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cardHeaderLayout.addItem(spacerItem)
        self.cardIcon = QtWidgets.QLabel(Card)
        self.cardIcon.setMinimumSize(QtCore.QSize(32, 32))
        self.cardIcon.setMaximumSize(QtCore.QSize(32, 32))
        self.cardIcon.setStyleSheet("QLabel { background-color: #fce4ec; border-radius: 16px; padding: 6px; }")
        self.cardIcon.setText("")
        self.cardIcon.setScaledContents(True)
        self.cardIcon.setObjectName("cardIcon")
        self.cardHeaderLayout.addWidget(self.cardIcon)
        self.cardLayout.addLayout(self.cardHeaderLayout)
        self.cardValue = QtWidgets.QLabel(Card)
        self.cardValue.setStyleSheet("QLabel { font-size: 28px; font-weight: bold; color: #333333; }")
        self.cardValue.setObjectName("cardValue")
        self.cardLayout.addWidget(self.cardValue)
        self.cardSubtext = QtWidgets.QLabel(Card)
        self.cardSubtext.setStyleSheet("QLabel { font-size: 11px; color: #4caf50; }")
        self.cardSubtext.setObjectName("cardSubtext")
        self.cardLayout.addWidget(self.cardSubtext)

        self.retranslateUi(Card)
        QtCore.QMetaObject.connectSlotsByName(Card)

    def retranslateUi(self, Card):
        _translate = QtCore.QCoreApplication.translate
        self.cardTitle.setText(_translate("Card", "Titre"))
        self.cardValue.setText(_translate("Card", "0"))
        self.cardSubtext.setText(_translate("Card", "+0% depuis hier"))
