# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Harivony\Desktop\CakeFLow_Project\Cakeflow\app\ui\widgets\Header.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Header(object):
    def setupUi(self, Header):
        Header.setObjectName("Header")
        Header.resize(960, 70)
        Header.setMinimumSize(QtCore.QSize(0, 70))
        Header.setMaximumSize(QtCore.QSize(16777215, 70))
        Header.setStyleSheet("QFrame#Header {\n"
"    background-color: #ffffff;\n"
"    border-bottom: 1px solid #f0e0e8;\n"
"}")
        Header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.headerLayout = QtWidgets.QHBoxLayout(Header)
        self.headerLayout.setContentsMargins(20, -1, 20, -1)
        self.headerLayout.setObjectName("headerLayout")
        self.pageTitle = QtWidgets.QLabel(Header)
        self.pageTitle.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    color: #333333;\n"
"}")
        self.pageTitle.setObjectName("pageTitle")
        self.headerLayout.addWidget(self.pageTitle)
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.searchInput = QtWidgets.QLineEdit(Header)
        self.searchInput.setMinimumSize(QtCore.QSize(250, 36))
        self.searchInput.setMaximumSize(QtCore.QSize(300, 36))
        self.searchInput.setStyleSheet("QLineEdit {\n"
"    background-color: #faf5f7;\n"
"    border: 1px solid #f0e0e8;\n"
"    border-radius: 18px;\n"
"    padding: 6px 15px;\n"
"    font-size: 13px;\n"
"    color: #333333;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #e91e90;\n"
"    background-color: #ffffff;\n"
"}")
        self.searchInput.setObjectName("searchInput")
        self.headerLayout.addWidget(self.searchInput)
        spacerItem1 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.headerLayout.addItem(spacerItem1)
        self.userInfoFrame = QtWidgets.QFrame(Header)
        self.userInfoFrame.setStyleSheet("QFrame#userInfoFrame {\n"
"    background-color: #fff0f3;\n"
"    border-radius: 18px;\n"
"    padding: 4px 12px;\n"
"}")
        self.userInfoFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.userInfoFrame.setObjectName("userInfoFrame")
        self.userInfoLayout = QtWidgets.QHBoxLayout(self.userInfoFrame)
        self.userInfoLayout.setContentsMargins(8, -1, 8, -1)
        self.userInfoLayout.setSpacing(8)
        self.userInfoLayout.setObjectName("userInfoLayout")
        self.userAvatar = QtWidgets.QLabel(self.userInfoFrame)
        self.userAvatar.setMinimumSize(QtCore.QSize(28, 28))
        self.userAvatar.setMaximumSize(QtCore.QSize(28, 28))
        self.userAvatar.setPixmap(QtGui.QPixmap(":/icons/user.svg"))
        self.userAvatar.setScaledContents(True)
        self.userAvatar.setStyleSheet("QLabel {\n"
"    background-color: #e91e90;\n"
"    border-radius: 14px;\n"
"    padding: 4px;\n"
"}")
        self.userAvatar.setObjectName("userAvatar")
        self.userInfoLayout.addWidget(self.userAvatar)
        self.userName = QtWidgets.QLabel(self.userInfoFrame)
        self.userName.setStyleSheet("QLabel {\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    color: #c2185b;\n"
"}")
        self.userName.setObjectName("userName")
        self.userInfoLayout.addWidget(self.userName)
        self.headerLayout.addWidget(self.userInfoFrame)

        self.retranslateUi(Header)
        QtCore.QMetaObject.connectSlotsByName(Header)

    def retranslateUi(self, Header):
        _translate = QtCore.QCoreApplication.translate
        self.pageTitle.setText(_translate("Header", "Tableau de bord"))
        self.searchInput.setPlaceholderText(_translate("Header", "Rechercher..."))
        self.userName.setText(_translate("Header", "Admin"))
import resources_rc
