# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Harivony\Desktop\CakeFLow_Project\Cakeflow\app\ui\widgets\Sidebar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sidebar(object):
    def setupUi(self, Sidebar):
        Sidebar.setObjectName("Sidebar")
        Sidebar.resize(240, 800)
        Sidebar.setMinimumSize(QtCore.QSize(240, 0))
        Sidebar.setMaximumSize(QtCore.QSize(240, 16777215))
        Sidebar.setStyleSheet("QFrame#Sidebar {\n"
"    background-color: #ffffff;\n"
"    border-right: 1px solid #f0e0e8;\n"
"}")
        Sidebar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sidebarLayout = QtWidgets.QVBoxLayout(Sidebar)
        self.sidebarLayout.setContentsMargins(12, 15, 12, 15)
        self.sidebarLayout.setSpacing(4)
        self.sidebarLayout.setObjectName("sidebarLayout")
        self.logoFrame = QtWidgets.QFrame(Sidebar)
        self.logoFrame.setMinimumSize(QtCore.QSize(0, 60))
        self.logoFrame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.logoFrame.setStyleSheet("QFrame#logoFrame {\n"
"    border-bottom: 1px solid #fce4ec;\n"
"    padding-bottom: 10px;\n"
"}")
        self.logoFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logoFrame.setObjectName("logoFrame")
        self.logoLayout = QtWidgets.QHBoxLayout(self.logoFrame)
        self.logoLayout.setObjectName("logoLayout")
        self.sidebarLogo = QtWidgets.QLabel(self.logoFrame)
        self.sidebarLogo.setMinimumSize(QtCore.QSize(36, 36))
        self.sidebarLogo.setMaximumSize(QtCore.QSize(36, 36))
        self.sidebarLogo.setPixmap(QtGui.QPixmap(":/icons/cake.svg"))
        self.sidebarLogo.setScaledContents(True)
        self.sidebarLogo.setObjectName("sidebarLogo")
        self.logoLayout.addWidget(self.sidebarLogo)
        self.appName = QtWidgets.QLabel(self.logoFrame)
        self.appName.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #c2185b;\n"
"}")
        self.appName.setObjectName("appName")
        self.logoLayout.addWidget(self.appName)
        self.sidebarLayout.addWidget(self.logoFrame)
        spacerItem = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.sidebarLayout.addItem(spacerItem)
        self.btnDashboard = QtWidgets.QPushButton(Sidebar)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/dashboard.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDashboard.setIcon(icon)
        self.btnDashboard.setIconSize(QtCore.QSize(18, 18))
        self.btnDashboard.setMinimumSize(QtCore.QSize(0, 42))
        self.btnDashboard.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDashboard.setCheckable(True)
        self.btnDashboard.setChecked(True)
        self.btnDashboard.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    font-size: 13px;\n"
"    color: #666666;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #fff0f3;\n"
"    color: #c2185b;\n"
"}\n"
"QPushButton:checked {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #e91e90, stop:1 #c2185b);\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"}")
        self.btnDashboard.setObjectName("btnDashboard")
        self.sidebarLayout.addWidget(self.btnDashboard)
        self.btnCommandes = QtWidgets.QPushButton(Sidebar)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/commandes.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCommandes.setIcon(icon1)
        self.btnCommandes.setIconSize(QtCore.QSize(18, 18))
        self.btnCommandes.setMinimumSize(QtCore.QSize(0, 42))
        self.btnCommandes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCommandes.setCheckable(True)
        self.btnCommandes.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    font-size: 13px;\n"
"    color: #666666;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #fff0f3;\n"
"    color: #c2185b;\n"
"}\n"
"QPushButton:checked {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #e91e90, stop:1 #c2185b);\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"}")
        self.btnCommandes.setObjectName("btnCommandes")
        self.sidebarLayout.addWidget(self.btnCommandes)
        self.btnClients = QtWidgets.QPushButton(Sidebar)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/clients.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClients.setIcon(icon2)
        self.btnClients.setIconSize(QtCore.QSize(18, 18))
        self.btnClients.setMinimumSize(QtCore.QSize(0, 42))
        self.btnClients.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnClients.setCheckable(True)
        self.btnClients.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    font-size: 13px;\n"
"    color: #666666;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #fff0f3;\n"
"    color: #c2185b;\n"
"}\n"
"QPushButton:checked {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #e91e90, stop:1 #c2185b);\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"}")
        self.btnClients.setObjectName("btnClients")
        self.sidebarLayout.addWidget(self.btnClients)
        self.btnProduits = QtWidgets.QPushButton(Sidebar)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/produits.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnProduits.setIcon(icon3)
        self.btnProduits.setIconSize(QtCore.QSize(18, 18))
        self.btnProduits.setMinimumSize(QtCore.QSize(0, 42))
        self.btnProduits.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnProduits.setCheckable(True)
        self.btnProduits.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    font-size: 13px;\n"
"    color: #666666;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #fff0f3;\n"
"    color: #c2185b;\n"
"}\n"
"QPushButton:checked {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #e91e90, stop:1 #c2185b);\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"}")
        self.btnProduits.setObjectName("btnProduits")
        self.sidebarLayout.addWidget(self.btnProduits)
        self.btnPaiements = QtWidgets.QPushButton(Sidebar)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/paiements.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPaiements.setIcon(icon4)
        self.btnPaiements.setIconSize(QtCore.QSize(18, 18))
        self.btnPaiements.setMinimumSize(QtCore.QSize(0, 42))
        self.btnPaiements.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPaiements.setCheckable(True)
        self.btnPaiements.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    font-size: 13px;\n"
"    color: #666666;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #fff0f3;\n"
"    color: #c2185b;\n"
"}\n"
"QPushButton:checked {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #e91e90, stop:1 #c2185b);\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"}")
        self.btnPaiements.setObjectName("btnPaiements")
        self.sidebarLayout.addWidget(self.btnPaiements)
        self.btnContacts = QtWidgets.QPushButton(Sidebar)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/contacts.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnContacts.setIcon(icon5)
        self.btnContacts.setIconSize(QtCore.QSize(18, 18))
        self.btnContacts.setMinimumSize(QtCore.QSize(0, 42))
        self.btnContacts.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnContacts.setCheckable(True)
        self.btnContacts.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    font-size: 13px;\n"
"    color: #666666;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #fff0f3;\n"
"    color: #c2185b;\n"
"}\n"
"QPushButton:checked {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #e91e90, stop:1 #c2185b);\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"}")
        self.btnContacts.setObjectName("btnContacts")
        self.sidebarLayout.addWidget(self.btnContacts)
        spacerItem1 = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.sidebarLayout.addItem(spacerItem1)
        self.separatorLine = QtWidgets.QFrame(Sidebar)
        self.separatorLine.setMinimumSize(QtCore.QSize(0, 1))
        self.separatorLine.setMaximumSize(QtCore.QSize(16777215, 1))
        self.separatorLine.setStyleSheet("QFrame {\n"
"    background-color: #fce4ec;\n"
"}")
        self.separatorLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.separatorLine.setObjectName("separatorLine")
        self.sidebarLayout.addWidget(self.separatorLine)
        self.btnLogout = QtWidgets.QPushButton(Sidebar)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/logout.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLogout.setIcon(icon6)
        self.btnLogout.setIconSize(QtCore.QSize(18, 18))
        self.btnLogout.setMinimumSize(QtCore.QSize(0, 42))
        self.btnLogout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLogout.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    font-size: 13px;\n"
"    color: #999999;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #ffebee;\n"
"    color: #d32f2f;\n"
"}")
        self.btnLogout.setObjectName("btnLogout")
        self.sidebarLayout.addWidget(self.btnLogout)

        self.retranslateUi(Sidebar)
        QtCore.QMetaObject.connectSlotsByName(Sidebar)

    def retranslateUi(self, Sidebar):
        _translate = QtCore.QCoreApplication.translate
        self.appName.setText(_translate("Sidebar", "CakeFlow"))
        self.btnDashboard.setText(_translate("Sidebar", "  Tableau de bord"))
        self.btnCommandes.setText(_translate("Sidebar", "  Commandes"))
        self.btnClients.setText(_translate("Sidebar", "  Clients"))
        self.btnProduits.setText(_translate("Sidebar", "  Produits"))
        self.btnPaiements.setText(_translate("Sidebar", "  Paiements"))
        self.btnContacts.setText(_translate("Sidebar", "  Contacts"))
        self.btnLogout.setText(_translate("Sidebar", "  Déconnexion"))
import resources_rc
